### ISSUE TITLE
progress and done icons to the right of download buttons???

### ISSUE THREAD

**Issue by brazadas** [datasketch/dsmodules#23]
![Screenshot from 2020-03-26 12-51-09](https://user-images.githubusercontent.com/19413995/77679447-8c52c680-6f60-11ea-93d0-1985c04be683.png)
v.s.
![Screenshot from 2020-03-26 12-52-25](https://user-images.githubusercontent.com/19413995/77679551-ad1b1c00-6f60-11ea-8608-1833b0899406.png)

**Comment by jpmarindiaz** [comment]
Yes, please go ahead and fix
