### ISSUE TITLE
Make labels reactive in Download button

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/dsmodules#28]
Download button not rendered in the proper language

![image](https://user-images.githubusercontent.com/1489570/83166109-0a078f80-a0d4-11ea-824d-efb7397cce07.png)

**Comment by brazadas** [comment]
we talked about it: update function for modal button is needed (issue #71 shinypanels)

**Comment by brazadas** [comment]
This no longer apply I think this can be closed @jpmarindiaz
