### ISSUE TITLE
functions will must available for translation

### ISSUE THREAD

**Issue by CamilaAchury** [datasketch/dsmodules#29]
For example tableinput has text into function and I can't edit this

![imagen](https://user-images.githubusercontent.com/17035597/83365223-5c62dd80-a36c-11ea-8cdf-98ac5b85795c.png)

it must be possible to change the language of the module result

**Comment by brazadas** [comment]
jajaj ¿ya está cierto? @CamilaAchury

**Comment by brazadas** [comment]
@CamilaAchury: ¿lo cerramos?
