### ISSUE TITLE
add imageUploadInput

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/dsmodules#3]

**Comment by brazadas** [comment]
hice una rama en mi fork poner estas funciones y luego al pull request lo voy a linkear con este issue. ¿Qué nombre les pongo imageUploadInput, imageInput?

**Comment by jpmarindiaz** [comment]
ponle imageInput si no existe en otros paquetes, pega una googleada

**Comment by brazadas** [comment]
parece que no existe
