### ISSUE TITLE
Data seems to be stored in cache and doesn't update when uploading the same file with different data

### ISSUE THREAD

**Issue by marianaviro** [datasketch/dsmodules#54]
When uploading a data file and then trying to upload the same file but with different data or with modifications, the app doesn't update the data used to fill the table in Data view or to create the chart in Visualization view.

**Comment by jpmarindiaz** [comment]
@brazadas can you take a look? this is fixed by saving the uploaded file to a tmp dir (or time stamp) in `fileInput`

**Comment by brazadas** [comment]
i will take a look, yes
