### ISSUE TITLE
When downloading a visualization as PNG, the text has a different font and the quality of the image is very low

### ISSUE THREAD

**Issue by marianaviro** [datasketch/dsmodules#55]

**Comment by jpmarindiaz** [comment]
This is a big one. Need to review all the saving. @marianaviro Which visualization? interactive charts? or static?
We have issues with both. If you can provide a screenshot in the description thats better

**Comment by lenafm** [comment]
@marianaviro I was just reviewing the download quality and in the examples I tried it looks okay to me (see screenshot of the downloaded PNG from `app-simple-charts-orgs`). Do you remember which app you were using when you came across this issue? And do you think you might be able to provide a screenshot of when this occurs? Thanks! 
![image](https://user-images.githubusercontent.com/59022602/125273490-970aa980-e2d2-11eb-9c1b-6ac7e3ed1035.png)

**Comment by jpmarindiaz** [comment]
I think @CamilaAchuri fixed it and forgot to close the issue. @CamilaAchuri please confirm

**Comment by CamilaAchuri** [comment]
Yes, I adjusted this, what I don't know is if it is an optimal version.

**Comment by CamilaAchuri** [comment]
Eg: when de labels text is activate in the downloaded picture this texts not showing

**Comment by lenafm** [comment]
@CamilaAchuri which text isn't showing? Do you mind taking a screenshot of when this happens?
