### ISSUE TITLE
Error in tableInput module when I add sample data

### ISSUE THREAD

**Issue by CamilaAchury** [datasketch/dsmodules#59]
Hay un error q se genera cuando se usa tableInput, especificamente en el sampleData

 Warning: Error in <-: attempt to set an attribute on NULL

**Comment by jpmarindiaz** [comment]
Tienes que se más explícita. ¿En cuál selectizeInput pasa eso? ¿Dentro de cuál módulo?
¿Cuáles pasos hay que hacer para replicar el error?
@brazadas si entendiste está bien, si no tenemos que ser más explícitos en todos los issues que se pongan

**Comment by CamilaAchury** [comment]
Es que no se, se que hay un vacio en el modulo tableInput, justo en el código que se genera cuando se usa la opción de muestra de datos, o al menos, es lo que creo, porque no he logrado saber bien donde esta, pero aparece al correr cualquier app e ingresar esa opción

**Comment by brazadas** [comment]
creo que ese error es de hotr que se usa cada vez que hay un tableInput (para renderizar la tabla)
![Screenshot from 2020-09-17 15-20-57](https://user-images.githubusercontent.com/19413995/93523977-731c4880-f8f9-11ea-9aa8-f99facc68885.png)

**Comment by brazadas** [comment]
o mejor de homodatum

**Comment by jpmarindiaz** [comment]
Tratar de replicarlo y saber qué pasa en Homodatum para poner el issue allá

**Comment by brazadas** [comment]
sí

**Comment by brazadas** [comment]
@jpmarindiaz el error es en la función new_fringe de homodatum: se da cuando el argumento d es null. En las apps se da cuando se usa hotr (que llama a new_fringe) en el preview de los datos (tablas) subidos porque por los tiempos de shiny hay un momento en que estos datos son null. En las apps se arregla con un req; no sé si sea bueno poner el condicional con el stop en la función new_fringe y si es así, hay bastantes -fringe_d, fringe_dic- que necesitarían la misma excepción
