### ISSUE TITLE
Increase size of jpg and png downloads through webshot

### ISSUE THREAD

**Issue by lenafm** [datasketch/dsmodules#81]
The previews of visualisations in DS profiles are two small and out of proportion - increase size of jpg and png downloads of `highcharter` objects.

![image](https://user-images.githubusercontent.com/59022602/108848875-853c9a00-75af-11eb-95a3-cfc3af4ba74b.png)

**Comment by jpmarindiaz** [comment]
This is actually related with the possibility of having different preview sizes and aspect ratios for vis previews. We could have buttons to preview in different "sizes": Portrait, landscape and square.

**Comment by lenafm** [comment]
@jpmarindiaz at the moment the previews look fine, except they have different proportions than the original charts (e.g. title and subtitle font is bigger in relation to the actual graph, see screenshot). I feel like this works quite well for a preview, what do you think? Or should this be just a miniature version of the original, in the same proportions?

What are the portrait, landscape and square `buttons` referring to you mentioned in your last comment here? Should users be able to choose between these options?

 ![image.png](https://images.zenhubusercontent.com/5f59051ec7fe056b04bf556f/ceaad6ec-33a5-4227-b6a1-2f8779b793c6)

**Comment by jpmarindiaz** [comment]
The preview images should have the same proportions than the original chart. The fonts should look the same size as displayed on the screen to the user when they are tweaking the chart. 
At some point we should have a button that shows 3 aspect ratios for the user to choose, the chart should preview with the different aspect ratios and the preview image should look almost exactly as it was shown to the user.

**Comment by lenafm** [comment]
@jpmarindiaz Not sure I understand, shouldn't the font sizes be much smaller, to look good in the little preview boxes?
![image](https://user-images.githubusercontent.com/59022602/125293745-536f6a00-e2e9-11eb-9898-c2e2d96e24e3.png)
